
package service.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MessageSOAPImplService", targetNamespace = "http://ws.service/", wsdlLocation = "http://localhost:8080/LoginSOAPandREST/messageWS?wsdl")
public class MessageSOAPImplService
    extends Service
{

    private final static URL MESSAGESOAPIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MESSAGESOAPIMPLSERVICE_EXCEPTION;
    private final static QName MESSAGESOAPIMPLSERVICE_QNAME = new QName("http://ws.service/", "MessageSOAPImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/LoginSOAPandREST/messageWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MESSAGESOAPIMPLSERVICE_WSDL_LOCATION = url;
        MESSAGESOAPIMPLSERVICE_EXCEPTION = e;
    }

    public MessageSOAPImplService() {
        super(__getWsdlLocation(), MESSAGESOAPIMPLSERVICE_QNAME);
    }

    public MessageSOAPImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MESSAGESOAPIMPLSERVICE_QNAME, features);
    }

    public MessageSOAPImplService(URL wsdlLocation) {
        super(wsdlLocation, MESSAGESOAPIMPLSERVICE_QNAME);
    }

    public MessageSOAPImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MESSAGESOAPIMPLSERVICE_QNAME, features);
    }

    public MessageSOAPImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MessageSOAPImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MessageSOAPImpl
     */
    @WebEndpoint(name = "MessageSOAPImplPort")
    public MessageSOAPImpl getMessageSOAPImplPort() {
        return super.getPort(new QName("http://ws.service/", "MessageSOAPImplPort"), MessageSOAPImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MessageSOAPImpl
     */
    @WebEndpoint(name = "MessageSOAPImplPort")
    public MessageSOAPImpl getMessageSOAPImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.service/", "MessageSOAPImplPort"), MessageSOAPImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MESSAGESOAPIMPLSERVICE_EXCEPTION!= null) {
            throw MESSAGESOAPIMPLSERVICE_EXCEPTION;
        }
        return MESSAGESOAPIMPLSERVICE_WSDL_LOCATION;
    }

}
